### ISSUE TITLE
Rebound to the bottom upon change Orientation

### ISSUE THREAD

**Issue by AngleV** [Larphoid/android-Overscroll-ListView#5]
First of all i must say that this is a masterpiece of code my friend.

Now as far as the issue...  Try to populate about 100 for example items in the ListView.
Change the orientation to Landscape and to Scroll to the Bottom.
Change again the orientation to Portrait.  You will notice that the Last item is not shiting at the bottom of the ListView. For me the problem was solveb by adding the             mHandler.postDelayed(checkListviewTopAndBottom, delay) at the initializeValues function and it works perfectly.... please update your code accordingly

**Comment by Larphoid** [comment]
Thanks for notifying me of this issue. It so happens that I already made that modification myself, but had forgotten to update it to Gith !

**Comment by AngleV** [comment]
No prob Larphoid... keep coding !!!

By the way..any change to make a rebounce ScrollView also ??

**Comment by Larphoid** [comment]
I hadn't thought of that, but that might be pretty simple, as ScrollView and ListView have a lot of methods in common. Might be as simple as changing  "extends ListView" to "extends ScrollView" and seeing what needs to be changed if eclipse shows errors...
EDIT: well, turns out it isn't, because the key methods "onScroll" and "onScrollStateChanged" that i use from ListView do not exist for ScrollView :(
